name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '30 4 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Install osmium
      run: sudo apt-get install osmium-tool jq gpsbabel
    - name: Get the data and analyze
      run: |
        chmod +x ./*.sh
        ./download.sh
        ./undefined_recycling.sh
        ./phone_booths.sh
        ./osm_varios.sh
        ./remove.sh
      shell: bash 
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
